// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds(id, created_at, updated_at, name, url, user_id)
VALUES (
    $1,
    NOw(),
    NOw(),
    $2,
    $3,
    $4
) RETURNING id, created_at, updated_at, name, url, user_id
`

type CreateFeedParams struct {
	ID     uuid.UUID
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const feedList = `-- name: FeedList :many
SELECT name, url, user_id FROM feeds
`

type FeedListRow struct {
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) FeedList(ctx context.Context) ([]FeedListRow, error) {
	rows, err := q.db.QueryContext(ctx, feedList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedListRow
	for rows.Next() {
		var i FeedListRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
